tensorflow: [FIX]show proper error message when run `saved_model_cli` without arguments instead of an error said `AttributeError: 'Namespace' object has no attribute 'func'` (#12105)
Commit: 99bab71926d8b67fb1056b390445253a4a388070