tensorflow: Fixing what I think a bug introduced by cl/228373932, which resulted in some of our eval_test/eval_train jobs to fail with: AttributeError: 'NoneType' object has no attribute 'save_summary_steps'. Here's an example:
Commit: 7648a9554792d77a1506e39cc3a7bfc361126786