rails: will now return nil instead of raise a NoMethodError if the receiving object does not implement the method
Commit: 99ea1a875b06feb4346869f371e2a57a2cc0a0fc